Data

In [1]:
import pandas as pd
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', None)

The code below creates a dataframe from the Occupational Business License Data found [here](https://data.nola.gov/Economy-and-Workforce/Occupational-Business-Licenses/hjcd-grvu)

In [2]:
active_licenses = pd.read_csv("./Data/licenses.csv", header = None)
active_licenses.columns = active_licenses.loc[0].values.tolist()
active_licenses.drop(index = 0, inplace = True)
active_licenses.head()

,BusinessName,OwnerName,BusinessType,BusinessLicenseNumber,BusinessStartDate,Address,StreetNumber,StreetDirection,StreetName,StreetSuffix,Suite,City,State,Zip,PhoneNumber,MailAddress,MailSuite,MailCity,MailState,MailZip,Latitude,Longitude,Location
1,KINDRED INVESTIGATIONS,KINDRED INVESTIGATIONS INC.,1212 - HOME BASED-OFFICE USE ONLY,242228,02/19/2020,1334 ST ROCH AVE,1334,NaN,ST ROCH,AVE,NaN,NEW ORLEANS,LA,70117,NaN,1334 ST ROCH AVE,NaN,NEW ORLEANS,LA,70117,29.971651206495,-90.0525862225698,"(29.971651206495, -90.0525862225698)"
2,LEGIER & COMPANY APAC,LEGIER & MATERNE APAC,3344 - CERTIFIED PUBLIC ACCOUNTANTS,245139,01/01/1997,1100 POYDRAS ST,1100,NaN,POYDRAS,ST,3450,NEW ORLEANS,LA,70163,5045998388,1100 POYDRAS ST,3450,NEW ORLEANS,LA,70163,29.9499303373249,-90.075483218956,"(29.9499303373249, -90.075483218956)"
3,ASMINISTRATION OFFICE/NEW ORLEANS MISSION,"NEW ORLEANS MISSION, INC","2044 - COMMUNITY HOUSING SVCS, OTH",245161,01/01/2010,1134 BARONNE ST,1134,NaN,BARONNE,ST,NaN,NEW ORLEANS,LA,70113,5045232116,1134 BARONNE ST,NaN,NEW ORLEANS,LA,70113,29.9428477199858,-90.0760425545731,"(29.9428477199858, -90.0760425545731)"
4,TOTAL COMMUNITY ACTION INC,TOTAL COMMUNITY ACTION INC,"1401 - SOCIAL ADVOCACY ORGANIZATIONS, OTHER",242233,07/17/2015,1420 S JEFFERSON DAVIS PKWY,1420,S,JEFFERSON DAVIS,PKWY,NaN,NEW ORLEANS,LA,70125,5043303070,1420 S JEFFERSON DAVIS PKWY,NaN,NEW ORLEANS,LA,70125,29.9559760388089,-90.1050238200641,"(29.9559760388089, -90.1050238200641)"
5,MOBILE MINI INC,MOBILE MINI INC,3330 - CONSTR/MNG/FRSTRY MACH & EQP RNT/LSNG,242318,05/01/1999,9641 GENTILLY RD,9641,NaN,GENTILLY,RD,101,NEW ORLEANS,LA,70127,6028946311,4646 E VAN BUREN ST,STE 400,PHOENIX,AZ,85008,NaN,NaN,NaN

Since we are only interested in restaurants and bars, we need to filter by the following categories: full service restaurants (1105 - FULL SVC RESTAURANTS (TABLE SERVICE)), partial sevice restaurants((2062- LIMITED SVC RESTAURANTS (NO TABLE SERVICE)), and bars (1126 - DRINKING PLACES (ALCOHOLIC BEVERAGES)).

In [3]:
active_FS = active_licenses.copy().loc[active_licenses.BusinessType.isin(["1105 - FULL SVC RESTAURANTS (TABLE SERVICE)",
                                                                 "2062- LIMITED SVC RESTAURANTS (NO TABLE SERVICE)",
                                                                 "1126 - DRINKING PLACES (ALCOHOLIC BEVERAGES)"])]

active_FS.head()

,BusinessName,OwnerName,BusinessType,BusinessLicenseNumber,BusinessStartDate,Address,StreetNumber,StreetDirection,StreetName,StreetSuffix,Suite,City,State,Zip,PhoneNumber,MailAddress,MailSuite,MailCity,MailState,MailZip,Latitude,Longitude,Location
13,"TASTY TREAT, LLC","TASTY TREAT, LLC",1105 - FULL SVC RESTAURANTS (TABLE SERVICE),233384,09/29/2016,1900 NORTH CLAIBORNE AVENUE,1900,NORTH,CLAIBORNE,AVENUE,NaN,NEW ORLEANS,LA,70116,NaN,1900 NORTH CLAIBORNE AVENUE,NaN,NEW ORLEANS,LA,70116,NaN,NaN,NaN
17,MERMAIDS,MERMAIDS LLC,1105 - FULL SVC RESTAURANTS (TABLE SERVICE),244798,01/08/2019,8700 LAKE FOREST BLVD,8700,NaN,LAKE FOREST,BLVD,NaN,NEW ORLEANS,LA,70127,5042355513,531823 P.O. BOX,NaN,NEW ORLEANS,LA,70153,30.0277705105953,-89.9885260904688,"(30.0277705105953, -89.9885260904688)"
34,AUDUBON ZOO,"AUDUBON NATURE INSTITUTE, INC",1126 - DRINKING PLACES (ALCOHOLIC BEVERAGES),232009,10/01/1977,6500 MAGAZINE ST,6500,NaN,MAGAZINE,ST,NaN,NEW ORLEANS,LA,70118,5048612537,6500 MAGAZINE ST,NaN,NEW ORLEANS,LA,70118,29.9247123907783,-90.1281704516248,"(29.9247123907783, -90.1281704516248)"
37,JAKEL'S BACK STREET LOUNGE,JAKEL'S BACK STREET LOUNGE INC,1126 - DRINKING PLACES (ALCOHOLIC BEVERAGES),245136,06/21/2006,2613-15 JASMINE ST,2613-15,NaN,JASMINE,ST,NaN,NEW ORLEANS,LA,70127,NaN,11001 GUILDFORD RD,NaN,NEW ORLEANS,LA,70122,NaN,NaN,NaN
48,CLAIRE'S POUR HOUSE,NOEL REAL ESTATE LLC,1126 - DRINKING PLACES (ALCOHOLIC BEVERAGES),245186,04/25/2011,233 DECATUR ST,233,NaN,DECATUR,ST,NaN,NEW ORLEANS,LA,70130,5045588980,233 DECATUR ST,NaN,NEW ORLEANS,LA,70130,29.9535033912752,-90.0660110008797,"(29.9535033912752, -90.0660110008797)"

Also, this dataframe contains information that will likely not be used. To clean it up, 
we will drop several of the columns in the dataset. Also, we will change the index to the business name and fill all NaN values to zeroes.

In [4]:
active_FS.drop(["OwnerName","BusinessLicenseNumber",'StreetNumber', 'StreetDirection',
                          'StreetName', 'StreetSuffix', 'Suite', 'City', 'State','MailAddress',
                          'MailSuite', 'MailCity', 'MailState','MailZip', 'Latitude', 'Longitude'], 
                          axis = 1, inplace = True)
active_FS = active_FS.fillna(0)
active_FS.set_index("BusinessName", inplace = True)
active_FS.head()

,BusinessType,BusinessStartDate,Address,Zip,PhoneNumber,Location
BusinessName,,,,,,
"TASTY TREAT, LLC",1105 - FULL SVC RESTAURANTS (TABLE SERVICE),09/29/2016,1900 NORTH CLAIBORNE AVENUE,70116,0,0
MERMAIDS,1105 - FULL SVC RESTAURANTS (TABLE SERVICE),01/08/2019,8700 LAKE FOREST BLVD,70127,5042355513,"(30.0277705105953, -89.9885260904688)"
AUDUBON ZOO,1126 - DRINKING PLACES (ALCOHOLIC BEVERAGES),10/01/1977,6500 MAGAZINE ST,70118,5048612537,"(29.9247123907783, -90.1281704516248)"
JAKEL'S BACK STREET LOUNGE,1126 - DRINKING PLACES (ALCOHOLIC BEVERAGES),06/21/2006,2613-15 JASMINE ST,70127,0,0
CLAIRE'S POUR HOUSE,1126 - DRINKING PLACES (ALCOHOLIC BEVERAGES),04/25/2011,233 DECATUR ST,70130,5045588980,"(29.9535033912752, -90.0660110008797)"

From here, we will combine this data table with yellow page data from 2018 and 2019 yellow pages by merging on phone numbers. Around half of the current table has a phone number listed. While this isn't perfect, if a restaurant closed in the past 6 months, they will be in the 2019 yellow pages, but not in the active licenses set. We can also see more information like the new restaurants opened and so on. We have not processed the yellow page data yet, but it can be found [here](https://www.therealyellowpages.com/Greater-New-Orleans-LA-2019/Yellow-Pages/1/) in pdf form (to see a different year change the year in the url). Also, we have the restaurant and bar pages as txt files in the data folder of the notebook.

Once we know what restaurants closed down, we produce a map of the worst hit areas in the city by 
looking at the zipcode of the the businesses that closed and perform additional analysis.